steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/flowlink-project/github.com/flowlink/quickbooks_desktop_integration_testing:${SHORT_SHA}', '.']
- name: 'gcr.io/flowlink-project/github.com/flowlink/quickbooks_desktop_integration_testing:${SHORT_SHA}'
  args: ['/bin/sh', '/app/scripts/rspec-cb.sh']
