steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/flowlink-project/github.com/flowlink/${_DOCKERTAG}:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/flowlink-project/github.com/flowlink/${_DOCKERTAG}:${SHORT_SHA}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '${_CRNAME}', '--image', 'gcr.io/flowlink-project/github.com/flowlink/${_DOCKERTAG}:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'services', 'update-traffic', 'quickbooksdesktopintegrationdev', '--region', 'us-central1', '--platform', 'managed', '--to-latest']
