version: "2"
services:
  quickbooks-desktop-integration:
    build: .
    environment:
      - RAILS_ENV=development
      - AWS_ACCESS_KEY_ID=ENV[AWS_ACCESS_KEY_ID]
      - AWS_SECRET_ACCESS_KEY=ENV[AWS_SECRET_ACCESS_KEY]
      - AWS_REGION=ENV[AWS_REGION]
      - IDS_TO_LOG=ENV[IDS_TO_LOG]
