version: "2"
services:
  quickbooks-desktop-integration:
    ports:
      - '3001:5000'
    volumes:
      - ${PWD}:/app
    environment:
      - AWS_ACCESS_KEY_ID=ENV[AWS_ACCESS_KEY_ID]
      - AWS_SECRET_ACCESS_KEY=ENV[AWS_SECRET_ACCESS_KEY]
      - AWS_REGION=ENV[AWS_REGION]