version: "2"
services:
  quickbooks-desktop-integration:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - IDS_TO_LOG
    ports:
      - '3001:5000'
    volumes:
      - ${PWD}:/app
